# Generated by Django 4.0.4 on 2022-05-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_activitytype_foodpermeal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='carbohydrate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='total_fats',
            field=models.FloatField(default=0),
        ),
    ]
