# Generated by Django 4.0.4 on 2022-06-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_age_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
