# Generated by Django 4.0.4 on 2022-07-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profileinfoperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfoperday',
            name='date',
            field=models.DateField(),
        ),
    ]
