# Generated by Django 4.0.4 on 2022-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_profile_goal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calorie_goal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
