# Generated by Django 4.0.4 on 2022-07-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profile_calorie_goal_alter_profile_goal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='proteins',
            field=models.FloatField(default=0),
        ),
    ]
