# Generated by Django 4.0.4 on 2022-07-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_meal_calories_meal_carbs_meal_fats_meal_proteins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
    ]
